// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

// GetAllSourceTypes200ApplicationJSON - response
type GetAllSourceTypes200ApplicationJSON struct {
	Data   []shared.SourceType `json:"data,omitempty"`
	Status *string             `json:"status,omitempty"`
}

func (o *GetAllSourceTypes200ApplicationJSON) GetData() []shared.SourceType {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAllSourceTypes200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllSourceTypesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAllSourceTypes200ApplicationJSONObject *GetAllSourceTypes200ApplicationJSON
}

func (o *GetAllSourceTypesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllSourceTypesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllSourceTypesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllSourceTypesResponse) GetGetAllSourceTypes200ApplicationJSONObject() *GetAllSourceTypes200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAllSourceTypes200ApplicationJSONObject
}
