// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"

	"github.com/dashotv/tvdb/openapi/models/shared"
)

type GetAwardExtendedRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetAwardExtendedRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

// GetAwardExtended200ApplicationJSON - response
type GetAwardExtended200ApplicationJSON struct {
	// extended award record
	Data   *shared.AwardExtendedRecord `json:"data,omitempty"`
	Status *string                     `json:"status,omitempty"`
}

func (o *GetAwardExtended200ApplicationJSON) GetData() *shared.AwardExtendedRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAwardExtended200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAwardExtendedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAwardExtended200ApplicationJSONObject *GetAwardExtended200ApplicationJSON
}

func (o *GetAwardExtendedResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAwardExtendedResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAwardExtendedResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAwardExtendedResponse) GetGetAwardExtended200ApplicationJSONObject() *GetAwardExtended200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAwardExtended200ApplicationJSONObject
}
