// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

// GetAllArtworkTypes200ApplicationJSON - response
type GetAllArtworkTypes200ApplicationJSON struct {
	Data   []shared.ArtworkType `json:"data,omitempty"`
	Status *string              `json:"status,omitempty"`
}

func (o *GetAllArtworkTypes200ApplicationJSON) GetData() []shared.ArtworkType {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAllArtworkTypes200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllArtworkTypesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAllArtworkTypes200ApplicationJSONObject *GetAllArtworkTypes200ApplicationJSON
}

func (o *GetAllArtworkTypesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllArtworkTypesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllArtworkTypesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllArtworkTypesResponse) GetGetAllArtworkTypes200ApplicationJSONObject() *GetAllArtworkTypes200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAllArtworkTypes200ApplicationJSONObject
}
