// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"

	"github.com/dashotv/tvdb/openapi/models/shared"
)

type GetArtworkBaseRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetArtworkBaseRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

// GetArtworkBase200ApplicationJSON - response
type GetArtworkBase200ApplicationJSON struct {
	// base artwork record
	Data   *shared.ArtworkBaseRecord `json:"data,omitempty"`
	Status *string                   `json:"status,omitempty"`
}

func (o *GetArtworkBase200ApplicationJSON) GetData() *shared.ArtworkBaseRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetArtworkBase200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetArtworkBaseResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetArtworkBase200ApplicationJSONObject *GetArtworkBase200ApplicationJSON
}

func (o *GetArtworkBaseResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetArtworkBaseResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetArtworkBaseResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetArtworkBaseResponse) GetGetArtworkBase200ApplicationJSONObject() *GetArtworkBase200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetArtworkBase200ApplicationJSONObject
}
