// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

// GetAllMovieStatuses200ApplicationJSON - response
type GetAllMovieStatuses200ApplicationJSON struct {
	Data   []shared.Status `json:"data,omitempty"`
	Status *string         `json:"status,omitempty"`
}

func (o *GetAllMovieStatuses200ApplicationJSON) GetData() []shared.Status {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAllMovieStatuses200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllMovieStatusesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAllMovieStatuses200ApplicationJSONObject *GetAllMovieStatuses200ApplicationJSON
}

func (o *GetAllMovieStatusesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllMovieStatusesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllMovieStatusesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllMovieStatusesResponse) GetGetAllMovieStatuses200ApplicationJSONObject() *GetAllMovieStatuses200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAllMovieStatuses200ApplicationJSONObject
}
