// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

type GetAllPeopleRequest struct {
	// page number
	Page *float64 `queryParam:"style=form,explode=true,name=page"`
}

func (o *GetAllPeopleRequest) GetPage() *float64 {
	if o == nil {
		return nil
	}
	return o.Page
}

// GetAllPeople200ApplicationJSON - response
type GetAllPeople200ApplicationJSON struct {
	Data []shared.PeopleBaseRecord `json:"data,omitempty"`
	// Links for next, previous and current record
	Links  *shared.Links `json:"links,omitempty"`
	Status *string       `json:"status,omitempty"`
}

func (o *GetAllPeople200ApplicationJSON) GetData() []shared.PeopleBaseRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAllPeople200ApplicationJSON) GetLinks() *shared.Links {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *GetAllPeople200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllPeopleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAllPeople200ApplicationJSONObject *GetAllPeople200ApplicationJSON
}

func (o *GetAllPeopleResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllPeopleResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllPeopleResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllPeopleResponse) GetGetAllPeople200ApplicationJSONObject() *GetAllPeople200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAllPeople200ApplicationJSONObject
}
