// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

// GetAllCountries200ApplicationJSON - response
type GetAllCountries200ApplicationJSON struct {
	Data   []shared.Country `json:"data,omitempty"`
	Status *string          `json:"status,omitempty"`
}

func (o *GetAllCountries200ApplicationJSON) GetData() []shared.Country {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAllCountries200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllCountriesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAllCountries200ApplicationJSONObject *GetAllCountries200ApplicationJSON
}

func (o *GetAllCountriesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllCountriesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllCountriesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllCountriesResponse) GetGetAllCountries200ApplicationJSONObject() *GetAllCountries200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAllCountries200ApplicationJSONObject
}
