// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

// GetAllGenders200ApplicationJSON - response
type GetAllGenders200ApplicationJSON struct {
	Data   []shared.Gender `json:"data,omitempty"`
	Status *string         `json:"status,omitempty"`
}

func (o *GetAllGenders200ApplicationJSON) GetData() []shared.Gender {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAllGenders200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllGendersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAllGenders200ApplicationJSONObject *GetAllGenders200ApplicationJSON
}

func (o *GetAllGendersResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllGendersResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllGendersResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllGendersResponse) GetGetAllGenders200ApplicationJSONObject() *GetAllGenders200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAllGenders200ApplicationJSONObject
}
