// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

// GetAllArtworkStatuses200ApplicationJSON - response
type GetAllArtworkStatuses200ApplicationJSON struct {
	Data   []shared.ArtworkStatus `json:"data,omitempty"`
	Status *string                `json:"status,omitempty"`
}

func (o *GetAllArtworkStatuses200ApplicationJSON) GetData() []shared.ArtworkStatus {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAllArtworkStatuses200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllArtworkStatusesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAllArtworkStatuses200ApplicationJSONObject *GetAllArtworkStatuses200ApplicationJSON
}

func (o *GetAllArtworkStatusesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllArtworkStatusesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllArtworkStatusesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllArtworkStatusesResponse) GetGetAllArtworkStatuses200ApplicationJSONObject() *GetAllArtworkStatuses200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAllArtworkStatuses200ApplicationJSONObject
}
