// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"

	"github.com/dashotv/tvdb/openapi/models/shared"
)

// GetAllGenres200ApplicationJSON - response
type GetAllGenres200ApplicationJSON struct {
	Data   []shared.GenreBaseRecord `json:"data,omitempty"`
	Status *string                  `json:"status,omitempty"`
}

func (o *GetAllGenres200ApplicationJSON) GetData() []shared.GenreBaseRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAllGenres200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllGenresResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAllGenres200ApplicationJSONObject *GetAllGenres200ApplicationJSON
}

func (o *GetAllGenresResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllGenresResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllGenresResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllGenresResponse) GetGetAllGenres200ApplicationJSONObject() *GetAllGenres200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAllGenres200ApplicationJSONObject
}
