// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"

	"github.com/dashotv/tvdb/openapi/models/shared"
)

type GetAllCompaniesRequest struct {
	// name
	Page *float64 `queryParam:"style=form,explode=true,name=page"`
}

func (o *GetAllCompaniesRequest) GetPage() *float64 {
	if o == nil {
		return nil
	}
	return o.Page
}

// GetAllCompanies200ApplicationJSON - response
type GetAllCompanies200ApplicationJSON struct {
	Data []shared.Company `json:"data,omitempty"`
	// Links for next, previous and current record
	Links  *shared.Links `json:"links,omitempty"`
	Status *string       `json:"status,omitempty"`
}

func (o *GetAllCompanies200ApplicationJSON) GetData() []shared.Company {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAllCompanies200ApplicationJSON) GetLinks() *shared.Links {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *GetAllCompanies200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllCompaniesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAllCompanies200ApplicationJSONObject *GetAllCompanies200ApplicationJSON
}

func (o *GetAllCompaniesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllCompaniesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllCompaniesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllCompaniesResponse) GetGetAllCompanies200ApplicationJSONObject() *GetAllCompanies200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAllCompanies200ApplicationJSONObject
}
