// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

// GetAllPeopleTypes200ApplicationJSON - response
type GetAllPeopleTypes200ApplicationJSON struct {
	Data   []shared.PeopleType `json:"data,omitempty"`
	Status *string             `json:"status,omitempty"`
}

func (o *GetAllPeopleTypes200ApplicationJSON) GetData() []shared.PeopleType {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetAllPeopleTypes200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetAllPeopleTypesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetAllPeopleTypes200ApplicationJSONObject *GetAllPeopleTypes200ApplicationJSON
}

func (o *GetAllPeopleTypesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAllPeopleTypesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAllPeopleTypesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAllPeopleTypesResponse) GetGetAllPeopleTypes200ApplicationJSONObject() *GetAllPeopleTypes200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetAllPeopleTypes200ApplicationJSONObject
}
