// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

// GetCompanyTypes200ApplicationJSON - response
type GetCompanyTypes200ApplicationJSON struct {
	Data   []shared.CompanyType `json:"data,omitempty"`
	Status *string              `json:"status,omitempty"`
}

func (o *GetCompanyTypes200ApplicationJSON) GetData() []shared.CompanyType {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetCompanyTypes200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetCompanyTypesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetCompanyTypes200ApplicationJSONObject *GetCompanyTypes200ApplicationJSON
}

func (o *GetCompanyTypesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCompanyTypesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCompanyTypesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetCompanyTypesResponse) GetGetCompanyTypes200ApplicationJSONObject() *GetCompanyTypes200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetCompanyTypes200ApplicationJSONObject
}
