// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

type GetCompanyRequest struct {
	// id
	ID float64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetCompanyRequest) GetID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ID
}

// GetCompany200ApplicationJSON - response
type GetCompany200ApplicationJSON struct {
	// A company record
	Data   *shared.Company `json:"data,omitempty"`
	Status *string         `json:"status,omitempty"`
}

func (o *GetCompany200ApplicationJSON) GetData() *shared.Company {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetCompany200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetCompanyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetCompany200ApplicationJSONObject *GetCompany200ApplicationJSON
}

func (o *GetCompanyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCompanyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCompanyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetCompanyResponse) GetGetCompany200ApplicationJSONObject() *GetCompany200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetCompany200ApplicationJSONObject
}
