// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"

	"github.com/dashotv/tvdb/openapi/models/shared"
)

type GetCharacterBaseRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetCharacterBaseRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

// GetCharacterBase200ApplicationJSON - response
type GetCharacterBase200ApplicationJSON struct {
	// character record
	Data   *shared.Character `json:"data,omitempty"`
	Status *string           `json:"status,omitempty"`
}

func (o *GetCharacterBase200ApplicationJSON) GetData() *shared.Character {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetCharacterBase200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetCharacterBaseResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetCharacterBase200ApplicationJSONObject *GetCharacterBase200ApplicationJSON
}

func (o *GetCharacterBaseResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCharacterBaseResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCharacterBaseResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetCharacterBaseResponse) GetGetCharacterBase200ApplicationJSONObject() *GetCharacterBase200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetCharacterBase200ApplicationJSONObject
}
