// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"

	"github.com/dashotv/tvdb/openapi/models/shared"
)

// GetEntityTypes200ApplicationJSON - response
type GetEntityTypes200ApplicationJSON struct {
	Data   []shared.EntityType `json:"data,omitempty"`
	Status *string             `json:"status,omitempty"`
}

func (o *GetEntityTypes200ApplicationJSON) GetData() []shared.EntityType {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetEntityTypes200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetEntityTypesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetEntityTypes200ApplicationJSONObject *GetEntityTypes200ApplicationJSON
}

func (o *GetEntityTypesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetEntityTypesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetEntityTypesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetEntityTypesResponse) GetGetEntityTypes200ApplicationJSONObject() *GetEntityTypes200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetEntityTypes200ApplicationJSONObject
}
