// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

type GetListRequest struct {
	// id
	ID float64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetListRequest) GetID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ID
}

// GetList200ApplicationJSON - response
type GetList200ApplicationJSON struct {
	// base list record
	Data   *shared.ListBaseRecord `json:"data,omitempty"`
	Status *string                `json:"status,omitempty"`
}

func (o *GetList200ApplicationJSON) GetData() *shared.ListBaseRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetList200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetList200ApplicationJSONObject *GetList200ApplicationJSON
}

func (o *GetListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetListResponse) GetGetList200ApplicationJSONObject() *GetList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetList200ApplicationJSONObject
}
