// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

type GetListTranslationRequest struct {
	// id
	ID float64 `pathParam:"style=simple,explode=false,name=id"`
	// language
	Language string `pathParam:"style=simple,explode=false,name=language"`
}

func (o *GetListTranslationRequest) GetID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ID
}

func (o *GetListTranslationRequest) GetLanguage() string {
	if o == nil {
		return ""
	}
	return o.Language
}

// GetListTranslation200ApplicationJSON - response
type GetListTranslation200ApplicationJSON struct {
	Data   []shared.Translation `json:"data,omitempty"`
	Status *string              `json:"status,omitempty"`
}

func (o *GetListTranslation200ApplicationJSON) GetData() []shared.Translation {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetListTranslation200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetListTranslationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetListTranslation200ApplicationJSONObject *GetListTranslation200ApplicationJSON
}

func (o *GetListTranslationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetListTranslationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetListTranslationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetListTranslationResponse) GetGetListTranslation200ApplicationJSONObject() *GetListTranslation200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetListTranslation200ApplicationJSONObject
}
