// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

type GetListExtendedRequest struct {
	// id
	ID float64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetListExtendedRequest) GetID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ID
}

// GetListExtended200ApplicationJSON - response
type GetListExtended200ApplicationJSON struct {
	// extended list record
	Data   *shared.ListExtendedRecord `json:"data,omitempty"`
	Status *string                    `json:"status,omitempty"`
}

func (o *GetListExtended200ApplicationJSON) GetData() *shared.ListExtendedRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetListExtended200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetListExtendedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetListExtended200ApplicationJSONObject *GetListExtended200ApplicationJSON
}

func (o *GetListExtendedResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetListExtendedResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetListExtendedResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetListExtendedResponse) GetGetListExtended200ApplicationJSONObject() *GetListExtended200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetListExtended200ApplicationJSONObject
}
