// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

type GetListBySlugRequest struct {
	// slug
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *GetListBySlugRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

// GetListBySlug200ApplicationJSON - response
type GetListBySlug200ApplicationJSON struct {
	// base list record
	Data   *shared.ListBaseRecord `json:"data,omitempty"`
	Status *string                `json:"status,omitempty"`
}

func (o *GetListBySlug200ApplicationJSON) GetData() *shared.ListBaseRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetListBySlug200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetListBySlugResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetListBySlug200ApplicationJSONObject *GetListBySlug200ApplicationJSON
}

func (o *GetListBySlugResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetListBySlugResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetListBySlugResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetListBySlugResponse) GetGetListBySlug200ApplicationJSONObject() *GetListBySlug200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetListBySlug200ApplicationJSONObject
}
