// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

type GetMovieTranslationRequest struct {
	// id
	ID float64 `pathParam:"style=simple,explode=false,name=id"`
	// language
	Language string `pathParam:"style=simple,explode=false,name=language"`
}

func (o *GetMovieTranslationRequest) GetID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ID
}

func (o *GetMovieTranslationRequest) GetLanguage() string {
	if o == nil {
		return ""
	}
	return o.Language
}

// GetMovieTranslation200ApplicationJSON - response
type GetMovieTranslation200ApplicationJSON struct {
	// translation record
	Data   *shared.Translation `json:"data,omitempty"`
	Status *string             `json:"status,omitempty"`
}

func (o *GetMovieTranslation200ApplicationJSON) GetData() *shared.Translation {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetMovieTranslation200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetMovieTranslationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetMovieTranslation200ApplicationJSONObject *GetMovieTranslation200ApplicationJSON
}

func (o *GetMovieTranslationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetMovieTranslationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetMovieTranslationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetMovieTranslationResponse) GetGetMovieTranslation200ApplicationJSONObject() *GetMovieTranslation200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetMovieTranslation200ApplicationJSONObject
}
