// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

// GetPeopleExtendedMeta - meta
type GetPeopleExtendedMeta string

const (
	GetPeopleExtendedMetaTranslations GetPeopleExtendedMeta = "translations"
)

func (e GetPeopleExtendedMeta) ToPointer() *GetPeopleExtendedMeta {
	return &e
}

func (e *GetPeopleExtendedMeta) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "translations":
		*e = GetPeopleExtendedMeta(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetPeopleExtendedMeta: %v", v)
	}
}

type GetPeopleExtendedRequest struct {
	// id
	ID float64 `pathParam:"style=simple,explode=false,name=id"`
	// meta
	Meta *GetPeopleExtendedMeta `queryParam:"style=form,explode=true,name=meta"`
}

func (o *GetPeopleExtendedRequest) GetID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ID
}

func (o *GetPeopleExtendedRequest) GetMeta() *GetPeopleExtendedMeta {
	if o == nil {
		return nil
	}
	return o.Meta
}

// GetPeopleExtended200ApplicationJSON - response
type GetPeopleExtended200ApplicationJSON struct {
	// extended people record
	Data   *shared.PeopleExtendedRecord `json:"data,omitempty"`
	Status *string                      `json:"status,omitempty"`
}

func (o *GetPeopleExtended200ApplicationJSON) GetData() *shared.PeopleExtendedRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetPeopleExtended200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetPeopleExtendedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetPeopleExtended200ApplicationJSONObject *GetPeopleExtended200ApplicationJSON
}

func (o *GetPeopleExtendedResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetPeopleExtendedResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPeopleExtendedResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetPeopleExtendedResponse) GetGetPeopleExtended200ApplicationJSONObject() *GetPeopleExtended200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetPeopleExtended200ApplicationJSONObject
}
