// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

type GetSeriesBaseBySlugRequest struct {
	// slug
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *GetSeriesBaseBySlugRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

// GetSeriesBaseBySlug200ApplicationJSON - response
type GetSeriesBaseBySlug200ApplicationJSON struct {
	// The base record for a series. All series airs time like firstAired, lastAired, nextAired, etc. are in US EST for US series, and for all non-US series, the time of the showâ€™s country capital or most populous city. For streaming services, is the official release time. See https://support.thetvdb.com/kb/faq.php?id=29.
	Data   *shared.SeriesBaseRecord `json:"data,omitempty"`
	Status *string                  `json:"status,omitempty"`
}

func (o *GetSeriesBaseBySlug200ApplicationJSON) GetData() *shared.SeriesBaseRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetSeriesBaseBySlug200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetSeriesBaseBySlugResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetSeriesBaseBySlug200ApplicationJSONObject *GetSeriesBaseBySlug200ApplicationJSON
}

func (o *GetSeriesBaseBySlugResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSeriesBaseBySlugResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSeriesBaseBySlugResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSeriesBaseBySlugResponse) GetGetSeriesBaseBySlug200ApplicationJSONObject() *GetSeriesBaseBySlug200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetSeriesBaseBySlug200ApplicationJSONObject
}
