// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"

	"github.com/dashotv/tvdb/openapi/models/shared"
)

// GetSeasonTypes200ApplicationJSON - response
type GetSeasonTypes200ApplicationJSON struct {
	Data   []shared.SeasonType `json:"data,omitempty"`
	Status *string             `json:"status,omitempty"`
}

func (o *GetSeasonTypes200ApplicationJSON) GetData() []shared.SeasonType {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetSeasonTypes200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetSeasonTypesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetSeasonTypes200ApplicationJSONObject *GetSeasonTypes200ApplicationJSON
}

func (o *GetSeasonTypesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSeasonTypesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSeasonTypesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSeasonTypesResponse) GetGetSeasonTypes200ApplicationJSONObject() *GetSeasonTypes200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetSeasonTypes200ApplicationJSONObject
}
