// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"

	"github.com/dashotv/tvdb/openapi/models/shared"
)

type GetSeriesBaseRequest struct {
	// id
	ID float64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSeriesBaseRequest) GetID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ID
}

// GetSeriesBase200ApplicationJSON - response
type GetSeriesBase200ApplicationJSON struct {
	// The base record for a series. All series airs time like firstAired, lastAired, nextAired, etc. are in US EST for US series, and for all non-US series, the time of the showâ€™s country capital or most populous city. For streaming services, is the official release time. See https://support.thetvdb.com/kb/faq.php?id=29.
	Data   *shared.SeriesBaseRecord `json:"data,omitempty"`
	Status *string                  `json:"status,omitempty"`
}

func (o *GetSeriesBase200ApplicationJSON) GetData() *shared.SeriesBaseRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetSeriesBase200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetSeriesBaseResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetSeriesBase200ApplicationJSONObject *GetSeriesBase200ApplicationJSON
}

func (o *GetSeriesBaseResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSeriesBaseResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSeriesBaseResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSeriesBaseResponse) GetGetSeriesBase200ApplicationJSONObject() *GetSeriesBase200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetSeriesBase200ApplicationJSONObject
}
