// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dashotv/tvdb/openapi/models/shared"
	"net/http"
)

type GetSeriesNextAiredRequest struct {
	// id
	ID float64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSeriesNextAiredRequest) GetID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ID
}

// GetSeriesNextAired200ApplicationJSON - response
type GetSeriesNextAired200ApplicationJSON struct {
	// The base record for a series. All series airs time like firstAired, lastAired, nextAired, etc. are in US EST for US series, and for all non-US series, the time of the showâ€™s country capital or most populous city. For streaming services, is the official release time. See https://support.thetvdb.com/kb/faq.php?id=29.
	Data   *shared.SeriesBaseRecord `json:"data,omitempty"`
	Status *string                  `json:"status,omitempty"`
}

func (o *GetSeriesNextAired200ApplicationJSON) GetData() *shared.SeriesBaseRecord {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetSeriesNextAired200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetSeriesNextAiredResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetSeriesNextAired200ApplicationJSONObject *GetSeriesNextAired200ApplicationJSON
}

func (o *GetSeriesNextAiredResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSeriesNextAiredResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSeriesNextAiredResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSeriesNextAiredResponse) GetGetSeriesNextAired200ApplicationJSONObject() *GetSeriesNextAired200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetSeriesNextAired200ApplicationJSONObject
}
