// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"

	"github.com/dashotv/tvdb/openapi/models/shared"
)

// GetUserFavorites200ApplicationJSON - response
type GetUserFavorites200ApplicationJSON struct {
	Data   []shared.Favorites `json:"data,omitempty"`
	Status *string            `json:"status,omitempty"`
}

func (o *GetUserFavorites200ApplicationJSON) GetData() []shared.Favorites {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *GetUserFavorites200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetUserFavoritesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	GetUserFavorites200ApplicationJSONObject *GetUserFavorites200ApplicationJSON
}

func (o *GetUserFavoritesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetUserFavoritesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetUserFavoritesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetUserFavoritesResponse) GetGetUserFavorites200ApplicationJSONObject() *GetUserFavorites200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GetUserFavorites200ApplicationJSONObject
}
