// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostLoginRequestBody struct {
	Apikey string  `json:"apikey"`
	Pin    *string `json:"pin,omitempty"`
}

func (o *PostLoginRequestBody) GetApikey() string {
	if o == nil {
		return ""
	}
	return o.Apikey
}

func (o *PostLoginRequestBody) GetPin() *string {
	if o == nil {
		return nil
	}
	return o.Pin
}

type PostLogin200ApplicationJSONData struct {
	Token *string `json:"token,omitempty"`
}

func (o *PostLogin200ApplicationJSONData) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

// PostLogin200ApplicationJSON - response
type PostLogin200ApplicationJSON struct {
	Data   *PostLogin200ApplicationJSONData `json:"data,omitempty"`
	Status *string                          `json:"status,omitempty"`
}

func (o *PostLogin200ApplicationJSON) GetData() *PostLogin200ApplicationJSONData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *PostLogin200ApplicationJSON) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type PostLoginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// response
	PostLogin200ApplicationJSONObject *PostLogin200ApplicationJSON
}

func (o *PostLoginResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostLoginResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostLoginResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PostLoginResponse) GetPostLogin200ApplicationJSONObject() *PostLogin200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PostLogin200ApplicationJSONObject
}
